/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * ByteStorage provides LZ4 compression with xxHash3-64 integrity verification.
 *
 * This is a thin wrapper around cachekit-core's ByteStorage.
 */
export declare class ByteStorage {
  /** Create a new ByteStorage instance. */
  constructor()
  /**
   * Pack data with LZ4 compression and xxHash3-64 integrity checksum.
   *
   * # Arguments
   * * `data` - Raw bytes to pack
   *
   * # Returns
   * Packed bytes containing: [envelope with xxHash3-64 checksum + LZ4 compressed data]
   *
   * # Errors
   * Returns GenericFailure if compression fails
   */
  pack(data: Uint8Array): Uint8Array
  /**
   * Unpack data, verifying xxHash3-64 integrity and decompressing LZ4.
   *
   * # Arguments
   * * `packed` - Previously packed bytes from pack()
   *
   * # Returns
   * Original unpacked bytes
   *
   * # Errors
   * Returns GenericFailure if:
   * - Integrity check fails (data corrupted)
   * - Decompression fails (invalid format)
   */
  unpack(packed: Uint8Array): Uint8Array
  /**
   * Get compression ratio estimate for given data.
   *
   * # Arguments
   * * `data` - Data to estimate compression ratio for
   *
   * # Returns
   * Compression ratio (compressed_size / original_size)
   */
  estimateCompressionRatio(data: Uint8Array): number
  /**
   * Validate packed data without extracting.
   *
   * # Arguments
   * * `packed` - Previously packed bytes
   *
   * # Returns
   * true if valid, false otherwise
   */
  validate(packed: Uint8Array): boolean
}

/**
 * Per-tenant derived keys with automatic zeroization.
 *
 * This wraps cachekit-core's TenantKeys which has `#[derive(ZeroizeOnDrop)]`.
 * Keys are derived once and stay in Rust memory - never copied to JavaScript.
 *
 * # Security
 * - Keys are zeroized on drop (via cachekit-core's ZeroizeOnDrop)
 * - Clone is intentionally NOT implemented to prevent key proliferation
 * - Keys never leave Rust memory
 * - Encryptor is reused for nonce consistency (matches Python pattern)
 *
 * # Example
 * ```javascript
 * const tenantKeys = deriveTenantKeys(masterKey, 'tenant-123');
 * const ciphertext = encryptWithTenantKeys(plaintext, aad, tenantKeys);
 * const decrypted = decryptWithTenantKeys(ciphertext, aad, tenantKeys);
 * ```
 */
export declare class TenantKeys {
  /** Get the tenant ID these keys were derived for. */
  get tenantId(): string
  /** Get the encryption key fingerprint (safe to log/expose). */
  encryptionFingerprint(): Uint8Array
  /**
   * Get the current nonce counter value.
   *
   * Monitor this value for key rotation - rotate before reaching 2^32.
   * This matches Python's ZeroKnowledgeEncryptor.get_nonce_counter().
   */
  getNonceCounter(): number
}

/**
 * Decrypt ciphertext using TenantKeys (keys stay in Rust memory).
 *
 * Uses the encryptor stored in TenantKeys for consistency.
 *
 * With previous master keys configured (rotation grace window), decryption
 * runs cachekit-core's keyring loop: sequential attempts, current key
 * first, identical AAD every attempt. Only an AES-GCM authentication
 * failure advances to the next key; structural errors are terminal.
 *
 * # Arguments
 * * `ciphertext` - Previously encrypted data
 * * `aad` - Must match AAD used during encryption
 * * `tenant_keys` - Keys derived from deriveTenantKeys()
 *
 * # Returns
 * Original plaintext
 */
export declare function decryptWithTenantKeys(ciphertext: Uint8Array, aad: Uint8Array, tenantKeys: TenantKeys): Uint8Array

/**
 * Key derivation using HKDF-SHA256.
 *
 * Derives a 32-byte key from a master key, domain label, and tenant salt.
 * Uses HKDF (RFC 5869) for cryptographically secure derivation.
 *
 * # Arguments
 * * `master_key` - 32-byte master encryption key
 * * `domain` - Domain label (e.g., "cachekit:encryption") - cannot be empty
 * * `tenant_salt` - Per-tenant salt for isolation
 *
 * # Returns
 * 32-byte derived key
 *
 * # Errors
 * Returns InvalidArg if:
 * - master_key is not 32 bytes
 * - domain is empty
 * - tenant_salt is empty
 *
 * # Example
 * ```javascript
 * const masterKey = Buffer.from(process.env.MASTER_KEY, 'hex');
 * const derivedKey = deriveKey(masterKey, 'cachekit:encryption', 'tenant-123');
 * ```
 */
export declare function deriveKey(masterKey: Uint8Array, domain: string, tenantSalt: string): Uint8Array

/**
 * Derive per-tenant keys using HKDF-SHA256.
 *
 * This matches Python's `derive_tenant_keys()` exactly, deriving three keys:
 * - encryption_key (domain: "encryption")
 * - authentication_key (domain: "authentication")
 * - cache_key_salt (domain: "cache_keys")
 *
 * # Arguments
 * * `master_key` - 32-byte master encryption key
 * * `tenant_id` - Tenant identifier for key isolation
 * * `previous_master_keys` - Optional decrypt-only previous master keys
 *   (max 3, each 32 bytes) retained during a key-rotation grace window.
 *   Reads attempt keys sequentially, current first, identical AAD per
 *   attempt (protocol `spec/encryption.md` → "Key Rotation (Keyring)").
 *   Writes always use `master_key`.
 *
 * # Returns
 * TenantKeys object with derived keys (stays in Rust memory)
 *
 * # Errors
 * Returns InvalidArg if any key has the wrong length, more than 3 previous
 * keys are supplied (rejected, never truncated), or `master_key` also
 * appears in `previous_master_keys` (forward-only rule: a key that ever
 * encrypted is never re-promoted).
 *
 * # Example
 * ```javascript
 * const masterKey = Buffer.from(process.env.MASTER_KEY, 'hex');
 * const tenantKeys = deriveTenantKeys(masterKey, 'tenant-123');
 * // During a rotation grace window:
 * const rotating = deriveTenantKeys(newKey, 'tenant-123', [oldKey]);
 * ```
 */
export declare function deriveTenantKeys(masterKey: Uint8Array, tenantId: string, previousMasterKeys?: Array<Uint8Array> | undefined | null): TenantKeys

/**
 * Encrypt plaintext using TenantKeys (keys stay in Rust memory).
 *
 * This is the recommended API for multi-tenant encryption.
 * Keys are passed by reference and never copied to JavaScript.
 * Uses the encryptor stored in TenantKeys for consistent nonce tracking.
 *
 * # Arguments
 * * `plaintext` - Data to encrypt (max 100 MB)
 * * `aad` - Additional Authenticated Data (max 64 KB)
 * * `tenant_keys` - Keys derived from deriveTenantKeys()
 *
 * # Returns
 * Ciphertext containing: [nonce][tag][encrypted_data]
 */
export declare function encryptWithTenantKeys(plaintext: Uint8Array, aad: Uint8Array, tenantKeys: TenantKeys): Uint8Array

/** Version of the cachekit-core-ts package */
export declare function version(): string
