/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * ByteStorage provides LZ4 compression with xxHash3-64 integrity verification.
 *
 * This is a thin wrapper around cachekit-core's ByteStorage.
 */
export declare class ByteStorage {
  /** Create a new ByteStorage instance. */
  constructor()
  /**
   * Pack data with LZ4 compression and xxHash3-64 integrity checksum.
   *
   * # Arguments
   * * `data` - Raw bytes to pack
   *
   * # Returns
   * Packed bytes containing: [envelope with xxHash3-64 checksum + LZ4 compressed data]
   *
   * # Errors
   * Returns GenericFailure if compression fails
   */
  pack(data: Uint8Array): Uint8Array
  /**
   * Unpack data, verifying xxHash3-64 integrity and decompressing LZ4.
   *
   * # Arguments
   * * `packed` - Previously packed bytes from pack()
   *
   * # Returns
   * Original unpacked bytes
   *
   * # Errors
   * Returns GenericFailure if:
   * - Integrity check fails (data corrupted)
   * - Decompression fails (invalid format)
   */
  unpack(packed: Uint8Array): Uint8Array
  /**
   * Get compression ratio estimate for given data.
   *
   * # Arguments
   * * `data` - Data to estimate compression ratio for
   *
   * # Returns
   * Compression ratio (compressed_size / original_size)
   */
  estimateCompressionRatio(data: Uint8Array): number
  /**
   * Validate packed data without extracting.
   *
   * # Arguments
   * * `packed` - Previously packed bytes
   *
   * # Returns
   * true if valid, false otherwise
   */
  validate(packed: Uint8Array): boolean
}

/**
 * AES-256-GCM encryption with AAD binding.
 *
 * Key is stored at construction time and used for all operations.
 * This is a thin wrapper around cachekit-core's ZeroKnowledgeEncryptor.
 *
 * # Security
 * - Key must be exactly 32 bytes (256 bits)
 * - Nonce is auto-generated per encryption (never reuse)
 * - AAD binds ciphertext to context (prevents substitution attacks)
 *
 * # Example
 * ```javascript
 * const key = crypto.randomBytes(32);
 * const encryptor = new Encryptor(key);
 * const aad = Buffer.from('cache:my-key');
 * const ciphertext = encryptor.encrypt(plaintext, aad);
 * const decrypted = encryptor.decrypt(ciphertext, aad);
 * ```
 */
export declare class Encryptor {
  /**
   * Create a new Encryptor with the given 32-byte key.
   *
   * # Arguments
   * * `key` - Exactly 32 bytes (256 bits) encryption key
   *
   * # Errors
   * Returns InvalidArg if key is not exactly 32 bytes
   */
  constructor(key: Uint8Array)
  /**
   * Encrypt plaintext with AAD binding.
   *
   * # Arguments
   * * `plaintext` - Data to encrypt (max 100 MB)
   * * `aad` - Additional Authenticated Data (bound to ciphertext, max 64 KB)
   *
   * # Returns
   * Ciphertext containing: [nonce][tag][encrypted_data]
   *
   * # Errors
   * Returns GenericFailure if encryption fails
   *
   * # CRITICAL: Signature is encrypt(plaintext, aad) NOT encrypt(key, plaintext, aad)
   */
  encrypt(plaintext: Uint8Array, aad: Uint8Array): Uint8Array
  /**
   * Decrypt ciphertext and verify AAD.
   *
   * # Arguments
   * * `ciphertext` - Previously encrypted data
   * * `aad` - Must match AAD used during encryption
   *
   * # Returns
   * Original plaintext
   *
   * # Errors
   * Returns GenericFailure if:
   * - Decryption fails
   * - AAD verification fails (wrong context)
   */
  decrypt(ciphertext: Uint8Array, aad: Uint8Array): Uint8Array
  /**
   * Get the current nonce counter value.
   *
   * Useful for monitoring nonce exhaustion (should rotate key before 2^32).
   */
  getNonceCounter(): number
}

/**
 * State machine for zero-downtime key rotation.
 *
 * During rotation:
 * - New data is encrypted with the new key
 * - Old data can still be decrypted with the old key
 * - After rotation completes, only new key is used
 */
export declare class KeyRotationState {
  /** Create a new KeyRotationState with the current key. */
  constructor(key: Uint8Array)
  /**
   * Start rotation to a new key.
   *
   * The old key is preserved for decryption during transition.
   */
  startRotation(newKey: Uint8Array): void
  /** Complete the rotation, discarding the old key. */
  completeRotation(): void
  /** Check if rotation is in progress. */
  isRotating(): boolean
  /** Get the key to use for encryption (always the current key). */
  encryptionKey(): Uint8Array
  /**
   * Get the key to try for decryption.
   * Returns current key, or previous key if rotation is in progress.
   *
   * During rotation, try current key first, then previous key.
   */
  decryptionKey(): Uint8Array
  /** Get the previous key (if rotation is in progress). */
  previousDecryptionKey(): Uint8Array | null
}

/**
 * Per-tenant derived keys with automatic zeroization.
 *
 * This wraps cachekit-core's TenantKeys which has `#[derive(ZeroizeOnDrop)]`.
 * Keys are derived once and stay in Rust memory - never copied to JavaScript.
 *
 * # Security
 * - Keys are zeroized on drop (via cachekit-core's ZeroizeOnDrop)
 * - Clone is intentionally NOT implemented to prevent key proliferation
 * - Keys never leave Rust memory
 * - Encryptor is reused for nonce consistency (matches Python pattern)
 *
 * # Example
 * ```javascript
 * const tenantKeys = deriveTenantKeys(masterKey, 'tenant-123');
 * const ciphertext = encryptWithTenantKeys(plaintext, aad, tenantKeys);
 * const decrypted = decryptWithTenantKeys(ciphertext, aad, tenantKeys);
 * ```
 */
export declare class TenantKeys {
  /** Get the tenant ID these keys were derived for. */
  get tenantId(): string
  /** Get the encryption key fingerprint (safe to log/expose). */
  encryptionFingerprint(): Uint8Array
  /**
   * Get the current nonce counter value.
   *
   * Monitor this value for key rotation - rotate before reaching 2^32.
   * This matches Python's ZeroKnowledgeEncryptor.get_nonce_counter().
   */
  getNonceCounter(): number
}

/**
 * Decrypt ciphertext using TenantKeys (keys stay in Rust memory).
 *
 * Uses the encryptor stored in TenantKeys for consistency.
 *
 * # Arguments
 * * `ciphertext` - Previously encrypted data
 * * `aad` - Must match AAD used during encryption
 * * `tenant_keys` - Keys derived from deriveTenantKeys()
 *
 * # Returns
 * Original plaintext
 */
export declare function decryptWithTenantKeys(ciphertext: Uint8Array, aad: Uint8Array, tenantKeys: TenantKeys): Uint8Array

/**
 * Key derivation using HKDF-SHA256.
 *
 * Derives a 32-byte key from a master key, domain label, and tenant salt.
 * Uses HKDF (RFC 5869) for cryptographically secure derivation.
 *
 * # Arguments
 * * `master_key` - 32-byte master encryption key
 * * `domain` - Domain label (e.g., "cachekit:encryption") - cannot be empty
 * * `tenant_salt` - Per-tenant salt for isolation - REQUIRED for multi-tenant security
 *
 * # Returns
 * 32-byte derived key
 *
 * # Errors
 * Returns InvalidArg if:
 * - master_key is not 32 bytes
 * - domain is empty
 * - tenant_salt is null/undefined or empty string
 *
 * # Example
 * ```javascript
 * const masterKey = Buffer.from(process.env.MASTER_KEY, 'hex');
 * const derivedKey = deriveKey(masterKey, 'cachekit:encryption', 'tenant-123');
 * ```
 */
export declare function deriveKey(masterKey: Uint8Array, domain: string, tenantSalt?: string | undefined | null): Uint8Array

/**
 * Derive per-tenant keys using HKDF-SHA256.
 *
 * This matches Python's `derive_tenant_keys()` exactly, deriving three keys:
 * - encryption_key (domain: "encryption")
 * - authentication_key (domain: "authentication")
 * - cache_key_salt (domain: "cache_keys")
 *
 * # Arguments
 * * `master_key` - 32-byte master encryption key
 * * `tenant_id` - Tenant identifier for key isolation
 *
 * # Returns
 * TenantKeys object with derived keys (stays in Rust memory)
 *
 * # Example
 * ```javascript
 * const masterKey = Buffer.from(process.env.MASTER_KEY, 'hex');
 * const tenantKeys = deriveTenantKeys(masterKey, 'tenant-123');
 * ```
 */
export declare function deriveTenantKeys(masterKey: Uint8Array, tenantId: string): TenantKeys

/**
 * Encrypt plaintext using TenantKeys (keys stay in Rust memory).
 *
 * This is the recommended API for multi-tenant encryption.
 * Keys are passed by reference and never copied to JavaScript.
 * Uses the encryptor stored in TenantKeys for consistent nonce tracking.
 *
 * # Arguments
 * * `plaintext` - Data to encrypt (max 100 MB)
 * * `aad` - Additional Authenticated Data (max 64 KB)
 * * `tenant_keys` - Keys derived from deriveTenantKeys()
 *
 * # Returns
 * Ciphertext containing: [nonce][tag][encrypted_data]
 */
export declare function encryptWithTenantKeys(plaintext: Uint8Array, aad: Uint8Array, tenantKeys: TenantKeys): Uint8Array

/** Version of the cachekit-core-ts package */
export declare function version(): string
